name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secret
        run: echo ${{ secrets.ACCESS_TOKEN }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Login to registry
        run: doctl registry login -t ${{ secrets.ACCESS_TOKEN }}