name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd backend
          go build .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Login to registry
        run: doctl registry login -t ${{ secrets.ACCESS_TOKEN }}

      - name: Build image
        run: |
          cd backend
          docker build --tag backend .

      - name: Tag image
        run: docker tag backend registry.digitalocean.com/workflows-registry/backend/master

      - name: Push image
        run: docker push registry.digitalocean.com/workflows-registry/backend/master